version: "3.9"

services:
  app:
    init: true
    container_name: django
    build:
      context: .
      args:
       - DEV=true
    image: jango
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    #command: >
    #sh -c "python mysite/manage.py runserver 0.0.0.0:8000"
   
