version: "3.9"

services:
  proxy:
    init: true
    container_name: nginx
    build:
      context: ./nginx
      args:
       - DEV=true
    image: nginx_proxy
    restart: always
    networks:
      - pong_net
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=pong.42.fr
      - CERTS_PATH=/etc/ssl/certs/nginx.crt
      - CERTS_KEY_PATH=/etc/ssl/private/nginx.pem
  backend-auth:
    init: true
    container_name: django
    build:
      context: ./tutorial
      args:
       - DEV=true
    image: jango
    restart: always
    networks:
      - pong_net
    ports:
      - "8000:8000"
    volumes:
      - ./tutorial/app:/app
  backend-user:
    init: true
    container_name: restapi_framework
    build:
      context: ./restapi
      args:
       - DEV=true
    image: restapi_image
    restart: always
    networks:
      - pong_net
    ports:
      - "8001:8000"
    volumes:
      - ./restapi/rest:/rest

networks:
  pong_net:
    name: PongGame
