# Generated by Django 5.1.6 on 2025-02-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twofaapp", "0003_rename_user_id_userinfo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="twofa_stored",
            field=models.BooleanField(default=False),
        ),
    ]
